[project]
name = "talio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.30.0",
    "aiohttp>=3.14.3",
    "aiohttp-socks>=0.11.0",
    "aiosqlite>=0.22.1",
    "alembic>=1.19.0",
    "black>=26.5.1",
    "greenlet>=3.5.4",
    "openai>=2.53.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.51",
    "yookassa>=3.11.0",
]
