"""start project

Revision ID: 6dbef84239f5
Revises: a5a13f98bd54
Create Date: 2026-08-08 13:50:43.679682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbef84239f5'
down_revision: Union[str, Sequence[str], None] = 'a5a13f98bd54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ais', sa.Column('qwen_use', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ais', 'qwen_use')
    # ### end Alembic commands ###
